// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOfjZkNrjHI6XlNHz73E3DoP_et5KLLGc',
    appId: '1:953080877064:web:404898a7598826733e41bd',
    messagingSenderId: '953080877064',
    projectId: 'have-fund-c4d23',
    authDomain: 'have-fund-c4d23.firebaseapp.com',
    storageBucket: 'have-fund-c4d23.appspot.com',
    measurementId: 'G-NNQV0FM3S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByLkIXFHiU3GecR5S7yvROnZCfFTvE57s',
    appId: '1:953080877064:android:0b3fffdfd433ed7b3e41bd',
    messagingSenderId: '953080877064',
    projectId: 'have-fund-c4d23',
    storageBucket: 'have-fund-c4d23.appspot.com',
  );
}
